### ISSUE TITLE
El botón de continuar en el pause menú hace que salte un error de excepción

### ISSUE THREAD

**Issue by edgarmd1** [DumBell-Games/Oh-my-ghost#14]
![Captura de pantalla 2024-04-21 a las 11 49 16](https://github.com/DumBell-Games/Oh-my-ghost/assets/118179227/a1cbeaf3-ef86-4de0-8986-a4e056952f91)

**Comment by Ropuce** [comment]
De verdad, esto es un problema de programacion II... a estas alturas no deberia hacer falta dejarlo en manos de otra persona si supuestamente sabes programar.

Lo que tienes que hacer es encontrar el por que ese boton es nullptr (supongo que en algun momento se habra borrado la lista de GuiControl). Dado el codigo comentado que hay en la parte superior de la captura de pantalla supongo que es el caso

Edit: claro que peta si ademas en el CleanUp no se destruye apropiadamente a los botones del menu, lo cual deja datos corruptos en el GuiManager

**Comment by edgarmd1** [comment]
Roger, si estás mencionado en este hilo es porque es un BUG generado por TU codigo. Cuando Pau y yo estuvimos haciendo esto iba perfectamente. Tu decidiste cambiar cosas y desde entonces el código en este punto peta, por lo que, es TU error no el nuestro.

Saludos

**Comment by PauMenaTorres** [comment]
Roger, este bug deberías de arreglarlo tú, ya que después de todas tus modificaciones el error apareció de la nada, cuando en el código que había antes funcionaba perfectamente y no ocurría dicho error. Así que no nos asignes a Edgar y a mí un error causado por tu código.

Gracias

**Comment by Ropuce** [comment]
Para vuestra informacion, la razon por la que peta es porque desactivais 2 veces cada modulo con VUESTRO codigo, ademas de desactivar el modulo que esta en ese momento ejecutandose

Si vais a programar de esa forma, almenos poned un return true justo despues de desactivar manualmente los modulos

Por el amor de Arceus, EL PROBLEMA LO CAUSASTEIS VOSOTROS DESDE EL PRINCIPIO, A VER SI OS ENTERAIS. QUE OS FUNCIONE "bien" NO SIGNIFICA QUE REALMENTE ESTE BIEN

Edit: Ahora que me he calmado voy a explicaros por que "funciona" vuestro codigo

Los modulos no liberan memoria al cerrarlos ya que desactivasteis el CleanUp() de TODOS los modulos
![imatge](https://github.com/DumBell-Games/Oh-my-ghost/assets/49079760/74117e03-3422-464b-97fa-367427ff748d)

Supongo que lo dejasteis comentado porque en TitleMenu::CleanUp(), borrais los punteros GuiControl a lo bruto en vez de llamar a una funcion dentro  de GuiManager que se deshaga de ellos de una forma controlada, dejando un puñado de punteros que apuntan a memoria invalida y causando una fuga de memoria en GuiManager. A vosotros os parece que dejar comentado el CleanUp() no es malo, pero es literalmente una de las pocas cosas que va a hacer imposible desarrollar el juego, especialmente si hay que ir cambiando de mapa, ya que para liberar la memoria de un mapa para cargar otro hay que pasar por CleanUp(). Asi que no me vengais con historias de que la culpa es mia cuando sois vosotros los que crean codigo basura

Edit 2: La captura de pantalla ha sido hecha en vuestro ultimo commit "antes de que yo rompiera las cosas". He aplicado lo mismo que hice para que el juego volviera a arrancar despues del merge (sin mi codigo) y funciona perfectamente. Basicamente he quitado todas las llamadas a Disable y Enable que habia fuera de FadeToBlack y he cambiado la eliminacion directa de los GuiControl a una llamada a funcion de GuiManager que elimina los punteros tambien de la lista guardada ahi. Si hubierais aprendido a debuguear como os he dicho mas de 10 veces en el ultimo año esto no habria pasado
