### ISSUE TITLE
En el menú principal, si le das a continue el mapa no carga directamente

### ISSUE THREAD

**Issue by edgarmd1** [DumBell-Games/Oh-my-ghost#15]

**Comment by Ropuce** [comment]
El mapa se intenta cargar, pero hay algun problema con el propio .tmx
Cuando pulsas continuar no carga el primer mapa sino el segundo (puedes ver cuales mapas hay asignados en el config.xml)

De todas formas, ese boton a futuro lo que va a hacer es determinar el mapa a cargar a partir del archivo de guardado, asi que no hace falta que funcione aun
