### ISSUE TITLE
UI no implementada

### ISSUE THREAD

**Issue by edgarmd1** [DumBell-Games/Oh-my-ghost#2]
Falta añadir la pantalla de inicio del juego funcional con botones

**Comment by Ropuce** [comment]
Ya tenemos una primera version del menu principal, solo falta vincular las funciones correspondientes para el cambio de pantalla

**Comment by Ropuce** [comment]
Falta alinear los botones y que pasar el raton por encima muestre los botones correctamente marcados. Dicha parte la dejamos para la alpha por falta de tiempo.
