### ISSUE TITLE
Juego peta incluso con los videos puestos

### ISSUE THREAD

**Issue by Ropuce** [DumBell-Games/Oh-my-ghost#42]
He descargado todos los videos que hay en la carpeta de gdive al momento de publicar este mensaje, el juego peta despues del segundo video haga lo que haga. Probado en rama dev

**Comment by Ropuce** [comment]
Acabo de ver que el nombre del archivo y el que tiene en el codigo no coinciden
En gdrive: OhMyGhost_Cinematica_Context.avi
En ContextoSpringyP1.cpp: OhMyGhost_Cinematica_Context_PrimeraParte.avi

Edit: peta incluso con el nombre igual, solo que esta vez cuando llega a determinada parte del tercer video o se intenta saltar este

Edit2: si a vosotros os funciona, decidme como lo teneis montado, porque yo no he tocado absolutamente nada del codigo relacionado a los videos ni las primeras pantallas

**Comment by edgarmd1** [comment]
El código está bien, lo que se nos olvidó subir los dos videos nuevos. El cambio de nombre se debe a que hay otros dos videos nuevos. No caben en drive y los colgamos en MEGA. Los pongo en Discord
